name: CI
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: Windows
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 8.0.x
          dotnet-quality: 'preview'
      - name: Build
        run: dotnet build src --configuration Release
      - name: Upload packages
        uses: actions/upload-artifact@v3.1.3
        with:
          name: NuGet packages
          path: nugets/
          retention-days: 7
      - name: Install SQL Server
        uses: Particular/install-sql-server-action@v1.0.2
        with:
          connection-string-env-var: SQLServerConnectionString
          catalog: nservicebus
      - name: Run tests
        uses: Particular/run-tests-action@v1.6.0
